version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: nest-docker-postgres
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
