name: Build and Push Docker Image to Docker Hub

on:
  workflow_run:
    workflows: [ Test ]
    branches: [main]
    types: [ completed ]

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Sha short
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print image tag
        run: echo redbit17/test:${{ steps.sha_short.outputs.sha_short }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: redbit17/test:${{ steps.sha_short.outputs.sha_short }}